# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: esp32:esp32:m5stack_atoms3:CDCOnBoot=cdc
          arduino-platform: esp32:esp32@3.1.1
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          required-libraries: TinyGPSPlus@1.0.3,TFT_eSPI@2.5.43,QMC5883LCompass@1.2.3,M5Unified@0.2.4,M5GFX@0.2.6
          sketch-names: "*.ino"
          sketch-names-find-start: autopilot-*
          extra-arduino-cli-args: "--warnings default --build-property compiler.libraries.ldflags=-Wl,--allow-multiple-definition "
          set-build-path: true

      - name: Find versions
        run: |
          find /home/runner -name esptool\*
          find /home/runner -name boot_app0.bin
          ls -la /home/runner/
          ls -l /home/runner/.arduino15/packages/esp32/tools/esptool_py/*

